[package]
name = "day10"
version = "0.1.0"
authors = ["Marshall Polaris <marshall@pol.rs>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
